### ISSUE TITLE
Clarify replacement URL

### ISSUE THREAD

**Issue by akerl** [strava/go.strava#28]
Hi

Per the Readme, it looks like this repo has been deprecated. The URLs in the readme point to https://github.com/strava/developers.strava.com , which appears to be a typo (that link 404s, but https://developers.strava.com/ works).

That said, would it be possible to have the golang library be generated by y'all and pushed to this or another git repo when the API updates? Not having this code be go-get-able breaks the standard golang workflow.

**Comment by mfine30** [comment]
My guess is it should be pointing to: https://developers.strava.com/docs/#client-code

**Comment by tcarreira** [comment]
It would be nice to archive this repository after updating the README to the right URL
