### ISSUE TITLE
No way to get feed of friends' activities

### ISSUE THREAD

**Issue by cwayne18** [strava/go.strava#9]
Theres no obvious way to hit the GET https://www.strava.com/api/v3/activities/following endpoint

**Comment by paulmach** [comment]
weird that is was missing.  added it in https://github.com/strava/go.strava/commit/cc9ec49032b05846f77f761d9b4fd533e70e1abb

**Comment by neshala** [comment]
This is still not working for me.

In the file current_athlete.go
we have this:
`data, err := c.service.client.run("GET", "/athlete/activities", c.ops)`

and that works.

but this:
`data, err := c.service.client.run("GET", "/activities/following", c.ops)`

is not working, and I am getting the following output with my valid token that works on example above:

{
    "message": "Authorization Error",
    "errors": []
}

What is the correct API endpoint to get feed of my friends activities that i see on strava homepage web site?

**Comment by owlz84** [comment]
Any progress on this front? I'm seeking a similar API endpoint.
